import abc
from abc import ABC
from dataclasses import dataclass

class APIClient(ABC, metaclass=abc.ABCMeta): ...

@dataclass
class LiteLLMEmbeddingClient(APIClient):
    model_name: str = ...
    dimensions: int = ...
    base_url: str = ...
    client = ...
    def __post_init__(self) -> None: ...
    def __init__(self, model_name, dimensions, base_url) -> None: ...

@dataclass
class OpenAILLMClient(APIClient):
    base_url: str = ...
    model_name: str = ...
    client = ...
    def __post_init__(self) -> None: ...
    def __init__(self, base_url, model_name) -> None: ...
