from personal_graph.graph import GraphDB
from personal_graph.models import Node
from typing import Dict, List, Optional

class MemoryManager:
    graph: GraphDB
    def __init__(self, graph_db: GraphDB | None = ...) -> None: ...
    def __enter__(self) -> MemoryManager: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def store_event(self, text: str, metadata: Dict) -> None: ...
    def recall(self, query: str, k: int = 5) -> List[Node]: ...
