from typing import Any, Callable, Dict, List
from personal_graph.models import Node, Edge
from personal_graph.database.db import DB
from personal_graph.embeddings import EmbeddingsModel

CursorExecFunction = Callable[[Any, Any], Any]

class Postgres(DB):
    dsn: str
    embedding_dimension: int
    embedding_model: EmbeddingsModel
    def __init__(
        self,
        *,
        dsn: str = ...,
        embedding_dimension: int = ...,
        embedding_model: EmbeddingsModel | None = ...,
    ) -> None: ...
    def atomic(self, cursor_exec_fn: CursorExecFunction) -> Any: ...
    def initialize(self) -> None: ...
    def save(self) -> None: ...
    def fetch_node_embed_id(self, node_id: Any): ...
    def fetch_edge_embed_ids(self, id: Any): ...
    def all_connected_nodes(self, node_or_edge: Node | Edge) -> Any: ...
    def get_connections(self, identifier: Any) -> CursorExecFunction: ...
    def search_edge(self, source: Any, target: Any, attributes: Dict) -> Any: ...
    def add_node(self, label: str, attribute: Dict, id: Any) -> None: ...
    def add_edge(
        self, source: Any, target: Any, label: str, attributes: Dict
    ) -> None: ...
    def update_node(self, node: Node) -> None: ...
    def remove_node(self, id: Any) -> None: ...
    def search_node(self, node_id: Any) -> Any: ...
    def search_node_label(self, node_id: Any) -> Any: ...
    def traverse(
        self, source: Any, target: Any | None = None, with_bodies: bool = False
    ) -> List: ...
    def fetch_node_id(self, id: Any): ...
    def find_nodes_by_label(self, label: str): ...
    def graphviz_visualize(
        self,
        dot_file: str | None = ...,
        path: List[Any] = ...,
        connections: Any = ...,
        format: str = ...,
        exclude_node_keys: List[str] = ...,
        hide_node_key: bool = ...,
        node_kv: str = ...,
        exclude_edge_keys: List[str] = ...,
        hide_edge_key: bool = ...,
        edge_kv: str = ...,
    ) -> Any: ...
    def fetch_ids_from_db(self) -> List[str]: ...
    def search_indegree_edges(self, target: Any) -> List[Any]: ...
    def search_outdegree_edges(self, source: Any) -> List[Any]: ...
    def search_similar_nodes(self, embed_id, *, desc: bool, sort_by: str): ...
    def search_similar_edges(self, embed_id, *, desc: bool, sort_by: str): ...
    def search_node_type(self, label: str): ...
    def search_id_by_node_type(self, node_type: str): ...
